### ISSUE TITLE
Is it possible to fade songs a little better?

### ISSUE THREAD

**Issue by Quinncuatro** [mattiasahlsen/spotify-queue#1]
This is already super cool, and better than my last favorite app for this (Festify), but there's a significant bit of silence in between each song. Is there a way to factor in a user's setting for crossfade?

**Comment by mattiasahlsen** [comment]
Currently crossfade does not work, because the app decides the next song
after the current song is done playing. I could maybe reduce the waiting
time inbetween slightly but not 100%.

**Comment by mattiasahlsen** [comment]
Now fading should work
