### ISSUE TITLE
Manage queue for hoster ?

### ISSUE THREAD

**Issue by brnicot** [mattiasahlsen/spotify-queue#3]
Would it be possible to make the playlist hoster able to reorder queue & delete songs from it ?
Thanks for the app, which is already super cool ;)

**Comment by mattiasahlsen** [comment]
Thanks! I might look into it. Do you wanna help?

Den tis 14 apr. 2020 kl 00:04 skrev brnicot <notifications@github.com>:

**Comment by brnicot** [comment]
I'm not very comfortable with js/vue so I think I won't be really helpful :(
And I'd add to my idea list something to instant play a title in the playlist, by bumping it at first place (so then after the playlist continues in the correct order)

thx

**Comment by mattiasahlsen** [comment]
I don't think I will be able to do this. It's not possible to do since the queue is decided "on-the-fly", i.e. the queue only looks two songs forward. This is because it should always decide the next song randomly based on all the latest songs added to the queue.
